# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 03:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(editable=False, verbose_name='\u4e0b\u8f7d\u5730\u5740')),
                ('desc', models.CharField(max_length=200, null=True, verbose_name='\u63cf\u8ff0')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4f20\u65e5\u671f')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u7c7b\u578b\u540d')),
                ('desc', models.CharField(max_length=200, null=True, verbose_name='\u63cf\u8ff0')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(editable=False, verbose_name='\u4e0b\u8f7d\u5730\u5740')),
                ('desc', models.CharField(max_length=200, null=True, verbose_name='\u63cf\u8ff0')),
                ('primary', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u5c01\u9762\u56fe\u7247')),
                ('image', models.ImageField(upload_to=b'/media/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('unpublished', '\u672a\u53d1\u5e03'), ('published', '\u5df2\u53d1\u5e03'), ('to-publish', '\u5f85\u53d1\u5e03')], default='unpublished', max_length=15, verbose_name='\u53d1\u5e03\u72b6\u6001')),
                ('pub_date', models.DateTimeField(auto_now=True, validators=[utils.validators.validate_not_past], verbose_name='\u53d1\u5e03\u65e5\u671f')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='modify_date',
            new_name='last_edit',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=120, verbose_name='\u6807\u9898'),
        ),
        migrations.AddField(
            model_name='publishment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Article', verbose_name='\u6587\u7ae0'),
        ),
        migrations.AddField(
            model_name='publishment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Category', verbose_name='\u6240\u5c5e\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='publishment',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u5e03\u4eba'),
        ),
        migrations.AddField(
            model_name='figure',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Article', verbose_name='\u6240\u5c5e\u6587\u7ae0'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='publishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Publishment'),
        ),
    ]
